# Form implementation generated from reading ui file 'admin_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(285, 164)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 285, 164))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.menu_acc = QtWidgets.QPushButton(parent=self.frame)
        self.menu_acc.setGeometry(QtCore.QRect(30, 0, 131, 23))
        self.menu_acc.setObjectName("menu_acc")
        self.menu_menedger = QtWidgets.QPushButton(parent=self.frame)
        self.menu_menedger.setGeometry(QtCore.QRect(30, 30, 131, 23))
        self.menu_menedger.setObjectName("menu_menedger")
        self.free_req = QtWidgets.QPushButton(parent=self.frame)
        self.free_req.setGeometry(QtCore.QRect(30, 90, 131, 23))
        self.free_req.setObjectName("free_req")
        self.disconnect = QtWidgets.QPushButton(parent=self.frame)
        self.disconnect.setGeometry(QtCore.QRect(180, 110, 91, 21))
        self.disconnect.setObjectName("disconnect")
        self.list_menedgers = QtWidgets.QPushButton(parent=self.frame)
        self.list_menedgers.setGeometry(QtCore.QRect(30, 60, 131, 23))
        self.list_menedgers.setObjectName("pushButton_5")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Меню Администратора"))
        self.menu_acc.setText(_translate("Form", "Меню бухгалтера"))
        self.menu_menedger.setText(_translate("Form", "Меню менеджера"))
        self.free_req.setText(_translate("Form", "Свободный запрос"))
        self.disconnect.setText(_translate("Form", "Отключиться"))
        self.list_menedgers.setText(_translate("Form", "Список сотрудников"))