# Form implementation generated from reading ui file 'append_pact.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(415, 300)
        self.date_deal = QtWidgets.QLineEdit(parent=Form)
        self.date_deal.setGeometry(QtCore.QRect(180, 30, 231, 22))
        self.date_deal.setObjectName("date_deal")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 260, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(0, 280, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(0, 60, 151, 16))
        self.label_4.setObjectName("label_4")
        self.start_time = QtWidgets.QLineEdit(parent=Form)
        self.start_time.setGeometry(QtCore.QRect(180, 60, 231, 22))
        self.start_time.setObjectName("start_time")
        self.end_time = QtWidgets.QLineEdit(parent=Form)
        self.end_time.setGeometry(QtCore.QRect(180, 90, 231, 22))
        self.end_time.setObjectName("end_time")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(0, 90, 171, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 180, 231, 22))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(0, 180, 171, 16))
        self.label_6.setObjectName("label_6")
        self.id_apartment = QtWidgets.QLineEdit(parent=Form)
        self.id_apartment.setGeometry(QtCore.QRect(180, 150, 231, 22))
        self.id_apartment.setText("")
        self.id_apartment.setObjectName("id_apartment")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(0, 150, 161, 16))
        self.label_7.setObjectName("label_7")
        self.id_arendator = QtWidgets.QLineEdit(parent=Form)
        self.id_arendator.setGeometry(QtCore.QRect(180, 120, 231, 22))
        self.id_arendator.setText("")
        self.id_arendator.setObjectName("id_arendator")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(0, 120, 161, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(220, 270, 181, 24))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить договор"))
        self.label.setText(_translate("Form", "Внимание!!"))
        self.label_2.setText(_translate("Form", "Формат даты: ГГГГ-ММ-ДД"))
        self.label_3.setText(_translate("Form", "Дата заключения договора"))
        self.label_4.setText(_translate("Form", "Начало действия договора"))
        self.label_5.setText(_translate("Form", "Окончание действия договора"))
        self.label_6.setText(_translate("Form", "Месячная оплата"))
        self.label_7.setText(_translate("Form", "Идентификатор помещения"))
        self.label_8.setText(_translate("Form", "Идентификатор арендатора"))
        self.pushButton.setText(_translate("Form", "Добавить"))
