# Form implementation generated from reading ui file 'append_menedger_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 240, 161, 24))
        self.pushButton.setObjectName("pushButton")
        self.surname = QtWidgets.QLineEdit(parent=Form)
        self.surname.setGeometry(QtCore.QRect(110, 10, 271, 22))
        self.surname.setObjectName("surname")
        self.name = QtWidgets.QLineEdit(parent=Form)
        self.name.setGeometry(QtCore.QRect(110, 40, 271, 22))
        self.name.setObjectName("name")
        self.midle_name = QtWidgets.QLineEdit(parent=Form)
        self.midle_name.setGeometry(QtCore.QRect(110, 70, 271, 22))
        self.midle_name.setObjectName("midle_name")
        self.phone_numb = QtWidgets.QLineEdit(parent=Form)
        self.phone_numb.setGeometry(QtCore.QRect(110, 100, 271, 22))
        self.phone_numb.setObjectName("phone_numb")
        self.pasp_ser = QtWidgets.QLineEdit(parent=Form)
        self.pasp_ser.setGeometry(QtCore.QRect(110, 130, 271, 22))
        self.pasp_ser.setObjectName("pasp_ser")
        self.pasp_numb = QtWidgets.QLineEdit(parent=Form)
        self.pasp_numb.setGeometry(QtCore.QRect(110, 160, 271, 22))
        self.pasp_numb.setObjectName("pasp_numb")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить менеджера"))
        self.label.setText(_translate("Form", "Фамилия"))
        self.label_2.setText(_translate("Form", "Имя"))
        self.label_3.setText(_translate("Form", "Отчество"))
        self.label_4.setText(_translate("Form", "Номер телефона"))
        self.label_5.setText(_translate("Form", "Серия паспорта"))
        self.label_6.setText(_translate("Form", "Номер паспорта"))
        self.pushButton.setText(_translate("Form", "Добавить"))
