# Form implementation generated from reading ui file 'append_arendator_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.label_6.setObjectName("label_6")
        self.insert = QtWidgets.QPushButton(parent=Form)
        self.insert.setGeometry(QtCore.QRect(120, 270, 161, 24))
        self.insert.setObjectName("insert")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 49, 16))
        self.label_8.setObjectName("label_8")
        self.line_surname = QtWidgets.QLineEdit(parent=Form)
        self.line_surname.setGeometry(QtCore.QRect(110, 10, 281, 22))
        self.line_surname.setObjectName("line_surname")
        self.linename = QtWidgets.QLineEdit(parent=Form)
        self.linename.setGeometry(QtCore.QRect(110, 40, 281, 22))
        self.linename.setObjectName("linename")
        self.linemidle_name = QtWidgets.QLineEdit(parent=Form)
        self.linemidle_name.setGeometry(QtCore.QRect(110, 70, 281, 22))
        self.linemidle_name.setObjectName("linemidle_name")
        self.linephone = QtWidgets.QLineEdit(parent=Form)
        self.linephone.setGeometry(QtCore.QRect(110, 100, 281, 22))
        self.linephone.setObjectName("linephone")
        self.linepaspser = QtWidgets.QLineEdit(parent=Form)
        self.linepaspser.setGeometry(QtCore.QRect(110, 130, 281, 22))
        self.linepaspser.setObjectName("linepaspser")
        self.linepaspnumb = QtWidgets.QLineEdit(parent=Form)
        self.linepaspnumb.setGeometry(QtCore.QRect(110, 160, 281, 22))
        self.linepaspnumb.setObjectName("linepaspnumb")
        self.lineidfranch = QtWidgets.QLineEdit(parent=Form)
        self.lineidfranch.setGeometry(QtCore.QRect(110, 190, 281, 22))
        self.lineidfranch.setObjectName("lineidfranch")
        self.lineINN = QtWidgets.QLineEdit(parent=Form)
        self.lineINN.setGeometry(QtCore.QRect(110, 220, 281, 22))
        self.lineINN.setObjectName("lineINN")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить арендатора"))
        self.label.setText(_translate("Form", "Фамилия"))
        self.label_2.setText(_translate("Form", "Имя"))
        self.label_3.setText(_translate("Form", "Отчество"))
        self.label_4.setText(_translate("Form", "Номер телефона"))
        self.label_5.setText(_translate("Form", "Серия паспорта"))
        self.label_6.setText(_translate("Form", "Номер паспорта"))
        self.insert.setText(_translate("Form", "Добавить"))
        self.label_7.setText(_translate("Form", "Ключ франшизы"))
        self.label_8.setText(_translate("Form", "ИНН"))
