# Form implementation generated from reading ui file 'listworkers_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 400)
        self.back = QtWidgets.QPushButton(parent=Form)
        self.back.setGeometry(QtCore.QRect(590, 370, 131, 24))
        self.back.setObjectName("back")
        self.insert = QtWidgets.QPushButton(parent=Form)
        self.insert.setGeometry(QtCore.QRect(10, 370, 131, 24))
        self.insert.setObjectName("insert")
        self.delete_2 = QtWidgets.QPushButton(parent=Form)
        self.delete_2.setGeometry(QtCore.QRect(290, 370, 131, 24))
        self.delete_2.setObjectName("delete_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 711, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Список сотрудников"))
        self.back.setText(_translate("Form", "Назад"))
        self.insert.setText(_translate("Form", "Добавить сотрудника"))
        self.delete_2.setText(_translate("Form", "Удалить сотрудника"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Идентификатор"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Отчество"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Номер телефона"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Серия паспорта"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Номер паспорта"))
