# Form implementation generated from reading ui file 'menedger_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 226)
        self.disconnect = QtWidgets.QPushButton(parent=Form)
        self.disconnect.setGeometry(QtCore.QRect(290, 190, 91, 23))
        self.disconnect.setObjectName("disconnect")
        self.delete_arendator = QtWidgets.QPushButton(parent=Form)
        self.delete_arendator.setGeometry(QtCore.QRect(0, 80, 181, 23))
        self.delete_arendator.setObjectName("delete_arendator")
        self.append_arendator = QtWidgets.QPushButton(parent=Form)
        self.append_arendator.setGeometry(QtCore.QRect(0, 50, 181, 23))
        self.append_arendator.setObjectName("append_arendator")
        self.filter_apartmenrs = QtWidgets.QPushButton(parent=Form)
        self.filter_apartmenrs.setGeometry(QtCore.QRect(0, 110, 181, 21))
        self.filter_apartmenrs.setObjectName("update_arendator")
        self.list_apartment = QtWidgets.QPushButton(parent=Form)
        self.list_apartment.setGeometry(QtCore.QRect(200, 20, 181, 23))
        self.list_apartment.setObjectName("list_apartment")
        self.list_arendator = QtWidgets.QPushButton(parent=Form)
        self.list_arendator.setGeometry(QtCore.QRect(0, 140, 181, 23))
        self.list_arendator.setObjectName("list_arendator")
        self.append_pact = QtWidgets.QPushButton(parent=Form)
        self.append_pact.setGeometry(QtCore.QRect(200, 80, 181, 23))
        self.append_pact.setObjectName("append_pact")
        self.allert_arendator = QtWidgets.QPushButton(parent=Form)
        self.allert_arendator.setGeometry(QtCore.QRect(200, 140, 181, 23))
        self.allert_arendator.setObjectName("allert_arendator")
        self.look_metro = QtWidgets.QPushButton(parent=Form)
        self.look_metro.setGeometry(QtCore.QRect(200, 50, 181, 23))
        self.look_metro.setObjectName("look_metro")
        self.list_arendodatel = QtWidgets.QPushButton(parent=Form)
        self.list_arendodatel.setGeometry(QtCore.QRect(0, 20, 181, 23))
        self.list_arendodatel.setObjectName("list_arendodatel")
        self.list_pacts = QtWidgets.QPushButton(parent=Form)
        self.list_pacts.setGeometry(QtCore.QRect(200, 110, 181, 23))
        self.list_pacts.setObjectName("pushButton_2")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Меню менеджера"))
        self.disconnect.setText(_translate("Form", "Отключиться"))
        self.delete_arendator.setText(_translate("Form", "Удалить арендатора"))
        self.append_arendator.setText(_translate("Form", "Добавить арендатора"))
        self.filter_apartmenrs.setText(_translate("Form", "Помещения по фильтру"))
        self.list_apartment.setText(_translate("Form", "Список доступных помещений"))
        self.list_arendator.setText(_translate("Form", "Список арендаторов"))
        self.append_pact.setText(_translate("Form", "Добавить договор"))
        self.allert_arendator.setText(_translate("Form", "Предупредить арендатора"))
        self.look_metro.setText(_translate("Form", "Помещения по метро"))
        self.list_arendodatel.setText(_translate("Form", "Список арендодателей"))
        self.list_pacts.setText(_translate("Form", "Список документов"))