# Form implementation generated from reading ui file 'request_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 400)
        self.result_line = QtWidgets.QTextEdit(parent=Form)
        self.result_line.setGeometry(QtCore.QRect(10, 160, 481, 221))
        self.result_line.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.result_line.setReadOnly(True)
        self.result_line.setObjectName("result_line")
        self.request_line = QtWidgets.QTextEdit(parent=Form)
        self.request_line.setGeometry(QtCore.QRect(10, 10, 481, 61))
        self.request_line.setObjectName("request_line")
        self.request_line.setPlaceholderText("Введите ваш запрос...")
        self.send_button = QtWidgets.QPushButton(parent=Form)
        self.send_button.setGeometry(QtCore.QRect(10, 80, 75, 24))
        self.send_button.setObjectName("send_button")
        self.back_button = QtWidgets.QPushButton(parent=Form)
        self.back_button.setGeometry(QtCore.QRect(420, 80, 75, 24))
        self.back_button.setObjectName("back_button")
        self.error_line = QtWidgets.QTextEdit(parent=Form)
        self.error_line.setGeometry(QtCore.QRect(10, 110, 481, 41))
        self.error_line.setAutoFillBackground(False)
        self.error_line.setUndoRedoEnabled(False)
        self.error_line.setReadOnly(True)
        self.error_line.setObjectName("error_line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Свободный запрос"))
        self.send_button.setText(_translate("Form", "Отправить"))
        self.back_button.setText(_translate("Form", "Назад"))

