# Form implementation generated from reading ui file 'search_on_metro_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(532, 356)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 531, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(40, 260, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(40, 290, 131, 16))
        self.label_2.setObjectName("label_2")
        self.look = QtWidgets.QPushButton(parent=Form)
        self.look.setGeometry(QtCore.QRect(390, 330, 111, 24))
        self.look.setObjectName("look")
        self.linestation = QtWidgets.QLineEdit(parent=Form)
        self.linestation.setGeometry(QtCore.QRect(200, 260, 301, 22))
        self.linestation.setObjectName("linestation")
        self.lineline = QtWidgets.QLineEdit(parent=Form)
        self.lineline.setGeometry(QtCore.QRect(200, 290, 301, 22))
        self.lineline.setObjectName("lineline")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Помещения по метро"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Идентификатор"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Адрес"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Арендодатель"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Номер телефона"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Удалённость от метро"))
        self.label.setText(_translate("Form", "Введите  станцию метро"))
        self.label_2.setText(_translate("Form", "Введите название ветки"))
        self.look.setText(_translate("Form", "Просмотр"))
